### ISSUE TITLE
The sample code for a React project does not work

### ISSUE THREAD

**Issue by kshibayama** [tanekloc/tmsg#35]
Hi @tanekloc 

Thank you for publishing this project! Since I am working on i18n, this package is attractive due to its size and simplicity compared with other existing enormous libraries.

I tried to run the sample code for React. But unfortunately, it did not work.

## What I did
```
> cd ${pathToSampleCode}
> npm install
> npm start
```

## Error
Then, I got this error:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/6373952/216863242-3b0d7057-cb58-4110-9c91-598ed648c110.png">

It seems that `i18n.buildT(localeStr)` in `useEffect` does not work as expected.

Could you help me fix it?

**Comment by tanekloc** [comment]
Hi, I have a React example here https://github.com/tanekloc/tmsg/tree/main/examples/react-example From the error it looks like you didn't generate any locales yet: try pointing the compile command to the public folder: `npx tmsgx compile --outDir ./public/locales --localesDir ./locales`. In React, this is the location where static files can be fetched. Did it work?

**Comment by tanekloc** [comment]
Ah, I guess you are running my example? :) let me see.

**Comment by tanekloc** [comment]
Thanks for raising the issue! I have fixed it and updated the example in https://github.com/tanekloc/tmsg/pull/41 The problem was that I forgot to re-add the webpackIgnore comment in the dynamic imports the lib relies on so that imports from the public folder work.

**Comment by kshibayama** [comment]
@tanekloc Thanks! I have updated the code and now it's successfully running 👏
